services:

# NTFY
  ntfy:
    image: binwiederhier/ntfy:${VERSION_NTFY}
    container_name: ntfy
    restart: unless-stopped
    user: 1001:1001
    command:
      - serve
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    environment:
      NTFY_BASE_URL: ${ENV_NTFY_BASE_URL} 
      NTFY_AUTH_FILE: /var/lib/ntfy/user.db
      NTFY_AUTH_DEFAULT_ACCESS: "deny-all"
      NTFY_ATTACHMENT_CACHE:DIR: /var/lib/ntfy/attachments
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/ntfy/cache:/var/cache/ntfy
      - /home/docker/ntfy/etc:/etc/ntfy
      - /home/docker/ntfy/lib:/var/lib/ntfy
    networks:
      - net
      - caddy
    ports:
      - ${PORT1_NTFY}:80

# MOLLYSOCKET
  mollysocket:
    image: ghcr.io/mollyim/mollysocket:${VERSION_MOLLYSOCKET}
    container_name: mollysocket
    restart: unless-stopped
    command: server
    environment:
      - MOLLY_DB="/data/mollysocket.db"
      - MOLLY_ALLOWED_ENDPOINTS=["${ENV_NTFY_BASE_URL}"]
      - MOLLY_ALLOWED_UUIDS=["*"]
      - MOLLY_VAPID_PRIVKEY=${ENV_MOLLY_VAPID_PRIVKEY}
      - MOLLY_HOST=0.0.0.0
      - MOLLY_PORT=${PORT1_MOLLYSOCKET}
      - RUST_LOG=info
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/mollysocket/data:/data
    networks:
      - net
      - caddy
    ports:
      - ${PORT1_MOLLYSOCKET}:8020


networks:
  net:
    driver: bridge
  caddy:
    name: reverseproxy-stack_net
    external: true

